### ISSUE TITLE
using CLI

### ISSUE THREAD

**Issue by sk3lk0** [ninoseki/onyphe-rb#9]
why i cant use onyphe?
my steps:
gem install onyphe
nano /usr/local/bundle/gems/onyphe-0.2.1/lib/onyphe/api.rb
i change
def initialize(api_key = ENV["ONYPHE_API_KEY"])
to
def initialize(api_key = ENV["de69bbc293767637ad049cb17de30cdccfb058fa"])
save it

end
and when i use onyphe ip 8.8.8.8 i get message
Please set your API key as an environment variable `ONYPHE_API_KEY`

**Comment by ninoseki** [comment]
Please read the following articles.

- [The ENV object in Ruby](https://medium.com/rubycademy/the-env-object-6ffa6ed9a63c)
- [The Rubyist's Guide to Environment Variables](https://www.honeybadger.io/blog/ruby-guide-environment-variables/)

**Comment by sk3lk0** [comment]
i fix it 
export ONYPHE_API_KEY=de69bbc293767637ad049cb17de30cdccfb058fa
after this step all work.thanks
